spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/yingxueapp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: con.baizhi.entity
  mapper-locations: mapper/*Mapper.xml
